version: "3.3"
services:
  db: #container do mysql 
    image: mariadb:10.5.8 #from mariadb
    volumes: 
      - ./db_data:/var/lib/mariadb
    environment: 
      MARIADB_ROOT_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress 
      MARIADB_USER: matheus
      MARIADB_PASSWORD: secret
  wordpress: 
    depends_on:
      - db
    image: wordpress:latest
    ports: 
      - "8000:80"
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_USER: matheus
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}